### ISSUE TITLE
Latest VERISR code errors with latest VCDB data

### ISSUE THREAD

**Issue by sabade** [jayjacobs/verisr#14]
I'm not sure if this is the right place, but I am trying to take your latest verisr code and the latest VCDB data, and reproduce the results from chapter 7 of your book.
First, when the data is loaded,  a very large number of Warning messages are kicked out.  
Warning found trying to set 2, "actor.External" for "TRUE"
  length of assignment: 1 
  in 2 /Users/sbade1/Data/VerisR/singleVCDB/037B7432-60E7-4B1D-8904-0A1D513DB382.json 
<simpleWarning in set(veris, i = i, j = x, value = paste(nfield[[x]], collapse = ",")): Coerced 'character' RHS to 'logical' to match the column's type. Either change the target column to 'character' first (by creating a new 'character' vector length 2 (nrows of entire table) and assign that; i.e. 'replace' column), or coerce RHS to 'logical' (e.g. 1L, NA_[real|integer]_, as.*, etc) to make your intent clear and for speed. Or, set the column type correctly up front when you create the table and stick to it, please.>

Second, summary(vcdb)  gives  (i am using a subset of the data - 2 incidents - for illustrative purposes)
gives.

> summary(vcdb)
> 2 incidents in this object.
> < table of extent 0 x 4 >

And enums for any level of property returns

> x <- getenum(vcdb,"action")
> print(x) 
> data frame with 0 columns and 0 rows

**Comment by kaegeh** [comment]
Hello, I am also experimenting with Ch.07 of Data Driven Security, and am attempting to load the vcdb data. I am following the code strictly from the book, but I am returned this error
library(ggplot2)
library(scales)
library(rjson)
library(devtools)
install_github("verisr", "jayjacobs", force = TRUE)
library(verisr)

jsondir <- ("C:/Users/Kxnice/ch07/data/vcdb/")
vcdb <- json2veris(jsondir)

Error in fromJSON(json_str = x) : 
  unexpected escaped character '\d' at pos 2

Does anyone have any insight on the matter? Thank you in advance.
