### ISSUE TITLE
json2veris breaks with the current verisc-merged schema

### ISSUE THREAD

**Issue by tybyers** [jayjacobs/verisr#25]
Hey! Following along with your (excellent) book, chapter 7....

When I try to run the `json2veris` command (listing 7-6), I get the following error:

```
> jsondir <- 'data/vcdb/'
> vcdb <- json2veris(jsondir)
Error in fromJSON(json_str = x) : 
  unexpected escaped character '\d' at pos 2
```

Digging a little deeper into your source code, in the json2veris function, if I try to straight-up load the schema with the rjson package, this is where the issue is:
```
> x <- getURL("https://raw.githubusercontent.com/vz-risk/veris/master/verisc-merged.json")
> lschema <- rjson::fromJSON(json_str=x)
Error in rjson::fromJSON(json_str = x) : 
  unexpected escaped character '\d' at pos 2
```

I suspect at some point the verisc-merged schema changed and now can no longer by read.

My workaround was to find the *original* schema in the GH history https://raw.githubusercontent.com/vz-risk/veris/86e76f1e77e07480c54ac9cb11642711c98e9cf0/verisc-merged.json, found from https://github.com/vz-risk/veris/commits/master/verisc-merged.json, download that to local, and then run the `json2veris` function with a specification to that schema:

```
jsonfile <- 'data/orig-verisc-merged.json'
vcdb <- json2veris(dir = 'data/vcdb/', schema = jsonfile)
```

No doubt there is a more recent version I could have checked to see if it worked, but I didn't care to do the binary search to figure out what was the most recent one to work.

The above ran (with a number of warnings), and I was able to reproduce some answers from your book.

I guess, however, the upshot is that the `json2veris` function doesn't like the current schema.

**Comment by pawelsobala** [comment]
Unfortunately, this workaround doesn't work with the current version of the database https://github.com/vz-risk/VCDB. 

R shows following error:
`In [.data.table(outdf, , :=(column, tempcol), with = F) :
  with=FALSE together with := was deprecated in v1.9.4 released Oct 2014. Please wrap the LHS of := with parentheses; e.g., DT[,(myVar):=sum(b),by=a] to assign to column name(s) held in variable myVar. See ?':=' for other examples. As warned in 2014, this is now a warning.`

Any ideas/solutions how to tackle this issue? So that I can run the code from book but on the current version of the database.

**Comment by tybyers** [comment]
@kontiki9 and others -- a couple things here:

It appears that this package has been moved to the vz-risk account.  So now install the package from: https://github.com/vz-risk/verisr, using `devtools::install_github('vz-risk/verisr')`

Then, the new package still doesn't like the default schema online.  So, you should then clone the `veris` repo: https://github.com/vz-risk/veris 

Then, you can do the `json2versis` command by specifying the schema `verisc-merged.json` within that repo you just cloned.  

So, this works (albeit with many warnings):

```
vcdb.dir <- '../../VCDB/data/json/'
vcdb <- json2veris(vcdb.dir, progressbar = TRUE, schema = '../../veris/verisc-merged.json')
```

**Comment by tybyers** [comment]
I've submitted a PR to the vz-risk/verisr repo, which appears to be the main package location now.  (https://github.com/vz-risk/verisr/pull/15) 

Until that PR is accepted and merged, you may install the fixed package version from my GH using the following: `devtools::install_github('tybyers/verisr', ref = 'fix-schema-fetch-tbyers')`

I can confirm after doing this that I can run the examples in the Data-Driven Security book. However, there are many warnings due to data.table deprecations.  

Closing this issue.

**Comment by kaegeh** [comment]
Thank you @tybyers for responding to my post. Your workaround as per https://github.com/jayjacobs/verisr/issues/25, seem to solve this. Thank you!
